# -*- coding: utf-8 -*-
"""rag_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEJubThGblA-CiwYyafioFE5JD8MIXi_

# RAG with Two Chunking Strategies

*   List item
*   List item


simple RAG system comparing `RecursiveCharacterTextSplitter` vs `MarkdownHeaderTextSplitter`, served via a Gradio UI.

#Install packages
"""

!pip install -q \
  langchain-chroma \
  langchain-huggingface \
  langchain-text-splitters \
  sentence-transformers \
  chromadb \
  gradio \
  wikipedia

"""#1.Imports

"""

import torch
import wikipedia
from langchain_text_splitters import (
    RecursiveCharacterTextSplitter,
    MarkdownHeaderTextSplitter,
)
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from transformers import AutoTokenizer, AutoModelForCausalLM
import gradio as gr

"""## 2. Build the corpus

A handful of Wikipedia articles i am intrested in. Pick topics you actually want to query focused content makes the retrieval comparison more interesting.
"""

topics = [
    "Information theory",
    "Claude Shannon",
    "Machine learning",
    "Saudi Arabia",
    "Quantum computing",
    "Transformer (deep learning architecture)",
]

texts = []
for t in topics:
    try:
        page = wikipedia.page(t, auto_suggest=False)
        texts.append({"title": page.title, "content": page.content})
        print(f"OK   {page.title}  ({len(page.content)} chars)")
    except Exception as e:
        print(f"SKIP {t}: {e}")

markdown_texts = [f"# {t['title']}\n\n{t['content']}" for t in texts]
print(f"\nTotal documents: {len(markdown_texts)}")

"""## 3. Chunking method 1 — Recursive character splitter

Splits on a hierarchy of separators (paragraphs → lines → words → chars). Structure-agnostic — doesn't know about markdown headers, just tries to keep chunks near the target size.
medium articule that explains it pretty well.

http://medium.com/@nihalgupta65/understanding-recursive-chunking-in-rag-how-it-works-when-it-fails-and-how-to-think-about-it-489ce043b235
"""

recursive_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50,
)
docs_recursive = recursive_splitter.create_documents(markdown_texts)

print(f"Recursive chunker produced {len(docs_recursive)} chunks")
print("\nExample chunk:")
print(docs_recursive[0].page_content[:300])

print(docs_recursive[-1].page_content[:300])

"""## 4. Chunking method 2 Markdown header splitter

Splits at `#`, `##`, `###` boundaries and stores the header path as metadata. More structure aware and respects the document outline.

A secondary recursive splitter caps large sections at 500 chars so chunks stay comparable in size to method 1.
"""

md_splitter = MarkdownHeaderTextSplitter(
    headers_to_split_on=[
        ("#", "Header 1"),
        ("##", "Header 2"),
        ("###", "Header 3"),
    ]
)

docs_markdown = []
for text in markdown_texts:
    docs_markdown.extend(md_splitter.split_text(text))


secondary = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
docs_markdown = secondary.split_documents(docs_markdown)

print(f"Markdown chunker produced {len(docs_markdown)} chunks")
print("\nExample chunk metadata:", docs_markdown[0].metadata)
print("\nExample chunk:")
print(docs_markdown[0].page_content[:300])

"""## 5. Embed and create two vector stores


"""

embedding_function = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db_recursive = Chroma.from_documents(
    docs_recursive,
    embedding_function,
    collection_name="recursive",
    persist_directory="./chroma_recursive",
)

db_markdown = Chroma.from_documents(
    docs_markdown,
    embedding_function,
    collection_name="markdown",
    persist_directory="./chroma_markdown",
)

print("Both vector stores built.")

"""# 6. Load the language model

Qwen2.5-1.5B-Instruct: small (~3GB in fp16), ungated, strong at instruction following..


"""

MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    device_map="auto",
)
model.eval()
print(f"Loaded {MODEL_ID} on {model.device}")

"""## 7. The RAG function

Retrieves top-k chunks, formats them with the user question via the model's chat template, generates an answer.
"""

SYSTEM_PROMPT = (
    "You are a helpful assistant. Answer the user's question using only the provided context. "
    "If the context doesn't contain the answer, say so clearly."
)

def query_rag(question: str, db, k: int = 4):

    docs = db.similarity_search(question, k=k)
    context = "\n\n".join(doc.page_content for doc in docs)


    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {question}"},
    ]
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )
    answer = tokenizer.decode(
        outputs[0][inputs.input_ids.shape[1]:],
        skip_special_tokens=True,
    )
    return answer.strip(), docs



answer, retrieved = query_rag("Entropy?", db_recursive)
print("ANSWER:")
print(answer)
print("\nRETRIEVED CHUNKS:")
for i, d in enumerate(retrieved, 1):
    print(f"\n--- chunk {i} ---")
    print(d.page_content[:200], "...")

"""## 8. Gradio interface

Pick a chunking strategy, ask a question, see the answer and the retrieved chunks side by side. `share=True` produces a public link (~72h) you can send to your tutor.
"""

def answer_with_ui(question, chunker):
    db = db_recursive if chunker == "Recursive" else db_markdown
    answer, retrieved = query_rag(question, db)
    chunks_preview = "\n\n---\n\n".join(
        [f"[chunk {i+1}]\n{d.page_content}" for i, d in enumerate(retrieved)]
    )
    return answer, chunks_preview

demo = gr.Interface(
    fn=answer_with_ui,
    inputs=[
        gr.Textbox(label="Question", lines=2,
                   placeholder="Ask something about the corpus..."),
        gr.Radio(["Recursive", "Markdown Header"],
                 label="Chunking method", value="Recursive"),
    ],
    outputs=[
        gr.Textbox(label="Answer", lines=4),
        gr.Textbox(label="Retrieved chunks", lines=15),
    ],
    title="RAG: Recursive vs Markdown-Header Chunking",
    description="Compare retrieval quality between the two chunking strategies.",
)

demo.launch(share=True, debug=False)

